apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bgaft0fy4-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bgaft0fy4-java-quarkus-gitops